# Doci is a quick and dirty tool for turning your script into documentation
# that show explainations and code side by side, a.k.a. "semi-[literate programming](https://en.wikipedia.org/wiki/Literate_programming)".
# It is simple and language agnostic.
#
# This is very much a remix of [Pycco](https://github.com/pycco-docs/pycco),
# which itself is a Python port of [Docco](https://github.com/jashkenas/docco),
# the original lightweight literate programming tool.
#
# ![Screenshot of Doci output](./assets/screenshot.png)

# ## Rationale
#
# The intent of a program is to be read by humans, not just executed by computers, etc...
# But more importantly, **LLMs write lots of comments**, and a tool that turns them into documentation
# would make them doubly useful!
#
# By itself it's quite dumb and needs to rely on other tools. For example, `scripts/build.py`
# watches `doci.py` for changes and reruns it automatically, which
# is a very simple way to add file watching abilities to Doci.
# (Maybe this is a good thing, because it means Doci is not trying to do everything by itself.)
#
# It is also well-documented. Doci is <350 lines of code plus comments and generates its own documentation,
# so it should be quite easy to read, modify and extend.

# ## Usage
#
# Clone this repository. Doci's own documentation is generated by running
#
# ```bash
# uv run doci.py -m README.md -H index.html doci.py
# ```
# which will generate `README.md` and `index.html` from `doci.py`,
# given that `template.html` exists in the same folder.

# ## Code
import re
import argparse
from markdown_it import MarkdownIt
from mdit_py_plugins.footnote import footnote_plugin
import pygments
import pygments.formatters
import pygments.lexers
import pystache
from typing import TypedDict, List, Tuple
from dataclasses import dataclass


#### Utility functions
def running(f, iterable, init=None):
    """
    `running` calculates a running value from an iterable using a binary function `f`.
    """
    for x in iterable:
        init = x if init is None else f(init, x)
        yield init


def running_sum(iterable, init=None):
    """
    `running_sum` calculates the running sum of an iterable.

    ``` py
    >>> list(running_sum(range(5)))
    [0, 1, 3, 6, 10]

    >>> list(running_sum(range(5), 10))
    [10, 11, 13, 16, 20]

    ```
    """
    return running(lambda x, y: x + y, iterable, init)


def indent_size(s: str) -> int:
    # A string's `indent_size` is the number of leading spaces.
    for i, c in enumerate(s):
        if c != " ":
            return i
    return len(s)


def dedent(s: List[str]) -> List[str]:
    """
    `dedent` dedents a list of strings, removing the minimum leading whitespace
    from all visible lines. Invisible lines (empty or whitespace-only)
    are left unchanged.

    ``` py
    >>> dedent(["    4 spaces", "  2 spaces", "", "   3 spaces"])
    ['  4 spaces', '2 spaces', '', ' 3 spaces']

    ```
    """
    stripped = [line.strip() for line in s]
    min_indent = min(
        (indent_size(line) for line, st in zip(s, stripped) if st != ""), default=None
    )
    if min_indent is None:
        return s
    return [line[min_indent:] if st != "" else line for line, st in zip(s, stripped)]


#### Extracting chunks
def extract_chunks(
    code: str, comment_start: str, block_syms: Tuple[str, str]
) -> Tuple[List[str], List[str]]:
    """
    `extract_chunks` extracts doc and code chunks from a program. We return a list of chunks
    and a list of booleans indicating whether each chunk is a doc chunk.
    """
    lines = code.splitlines(keepends=True)
    lc = len(lines)  # line count
    # Contents are lines stripped from whitespaces and line breaks.
    contents = [line.strip() for line in lines]
    is_comment = [c.startswith(comment_start) for c in contents]
    is_block_comment, level = parse_block_comment(contents, block_syms)

    # Chunks are consecutive lines of the same type. Docs are chunks that are comments.
    is_doc = [
        is_comment[i] or is_block_comment[i] != 0 or level[i] != 0 for i in range(lc)
    ]
    # As a result, chunks are always interspersed, which means
    # for each two doc chunks there is a code chunk in between, and vice versa.
    is_chunk_top = [i == 0 or is_doc[i - 1] != is_doc[i] for i in range(lc)]
    chunk_top_loc = [i for i, v in enumerate(is_chunk_top) if v]
    chunk_bottom_loc = chunk_top_loc[1:] + [lc]

    # Doc chunks are stripped of its starting symbols and whitespaces,
    # while code chunks are left as is.
    def strip(i: int, s: str) -> str:
        if is_comment[i]:
            return contents[i].removeprefix(comment_start) + "\n"
        if is_block_comment[i] != 0:
            # We ignore all block comment lines!
            return ""
        if is_doc[i]:
            return contents[i] + "\n"
        return s

    chunk_lines = [strip(i, s) for i, s in enumerate(lines)]
    chunk_type = ["doc" if is_doc[i] else "code" for i in chunk_top_loc]
    chunks = [
        "".join(chunk_lines[i:j]) for i, j in zip(chunk_top_loc, chunk_bottom_loc)
    ]
    return chunk_type, chunks


def parse_block_comment(
    contents: List[str], block_syms: Tuple[str, str]
) -> Tuple[List[int], List[int]]:
    """
    `parse_block_comment` takes in a list of contents and parses out block comments.
    """
    # `is_block_comment` is 0 for non-block-comment lines,
    # 1 for a comment start line, and -1 for a comment end line.
    is_block_comment = [
        1 if c.startswith(block_syms[0]) else -1 if c.startswith(block_syms[1]) else 0
        for c in contents
    ]
    if block_syms[0] == block_syms[1]:
        # If the start and end of a block comment is one symbol,
        # every other symbol must be an end quote.
        block_comment_locs = [i for i, v in enumerate(is_block_comment) if v == 1]
        for i, p in enumerate(block_comment_locs):
            if i % 2 == 1:
                is_block_comment[p] = -1

    # `level` is the nesting level of block comments.
    def next_level(seen: int, v: int) -> int:
        # We don't handle recursive block_comments, because most languages don't support them.
        # If we do, we would need to increment `seen_quote` here.
        # Using `max`, this code works even if there are more end quotes than start quotes.
        return 1 if v == 1 else max(0, seen - 1) if v == -1 else seen

    level = list(running(next_level, is_block_comment, 0))
    return is_block_comment, level


#### Formatting
def highlight(code_chunks: List[str], language: str, comment_start: str) -> List[str]:
    """
    `highlight` turns a list of code chunks into HTML using pygments.
    The code chunks are merged and passed pygments in one go,
    which is more efficient than highlighting each chunk separately.
    """
    # Magic divider text and html adapted from pycco.
    divider_text = f"{comment_start}DIVIDER\n"
    divider_html = re.compile(rf'<span class="c[1]?">{comment_start}DIVIDER</span>')
    lexer = pygments.lexers.get_lexer_by_name(language)

    # To do this, we join all code chunks into a single program
    # with a piece of divider text in between,
    joined_code = divider_text.join(code_chunks)
    # highlight the whole thing using pygments,
    html_formatter = pygments.formatters.get_formatter_by_name("html")
    output = (
        pygments.highlight(joined_code, lexer, html_formatter)
        .replace('<div class="highlight"><pre>', "")
        .replace("</pre></div>", "")
    )
    # then split it into html to get the html for each code section.
    return [
        f'<div class="highlight"><pre>{s}</pre></div>'
        for s in re.split(divider_html, output)
    ]


def to_markdown(chunk_type: List[str], chunks: List[str], language: str) -> str:
    """
    `to_markdown` convert chunks to markdown.
    """
    md = []
    for i, chunk in enumerate(chunks):
        if chunk_type[i] == "doc":
            # Doc chunks are dedented.
            md.append("".join(dedent(chunk.splitlines(keepends=True))))
        else:
            # Code chunks are stripped of trailing spaces and newlines.
            stripped = chunk.rstrip()
            if stripped != "":
                md.append(f"```{language}\n{chunk.rstrip()}\n```\n")
    return "\n".join(md)


def to_html(
    chunk_type: List[str],
    chunks: List[str],
    language: str,
    file_name: str,
    template: str,
) -> str:
    """
    `to_html` convert chunks to HTML.
    """
    # Code is parsed using pygments.
    code_locs = [i for i, t in enumerate(chunk_type) if t == "code"]
    code_html = highlight([chunks[i] for i in code_locs], language, "#")

    # Docs are parsed using markdown-it according to the commonmark spec
    # with tables and footnotes enabled.
    docs_locs = [i for i, t in enumerate(chunk_type) if t == "doc"]
    md = MarkdownIt("commonmark").use(footnote_plugin).enable("table")
    docs_html = [md.render(chunks[i]) for i in docs_locs]

    html = [""] * len(chunks)
    for i, v in zip(code_locs, code_html):
        html[i] = v
    for i, v in zip(docs_locs, docs_html):
        html[i] = v
    # Pair the doc and code chunks together.
    sections = []
    doc, code = "", ""
    for i, s in enumerate(html):
        if chunk_type[i] == "doc" and doc != "":
            sections.append((doc, code))
            doc, code = "", ""
        elif chunk_type[i] == "code" and code != "":
            sections.append((doc, code))
            doc, code = "", ""
        doc, code = (s, code) if chunk_type[i] == "doc" else (doc, s)
    sections.append((doc, code))
    return pystache.render(
        template,
        {
            "title": file_name,
            "sections": [
                {
                    "num": i + 1,
                    "doc": doc,
                    "code": code,
                }
                for i, (doc, code) in enumerate(sections)
            ],
        },
    )


#### Command line interface
def main():
    parser = argparse.ArgumentParser(description="A simple literate programming tool.")
    # TODO: add rationale for the arguments
    parser.add_argument(
        "-m",
        "--markdown",
        type=argparse.FileType("w"),
        nargs="?",
        const=False,
        help="generate markdown output",
    )
    parser.add_argument(
        "-H",
        "--html",
        type=argparse.FileType("w"),
        nargs="?",
        const=False,
        help="generate HTML output",
    )
    parser.add_argument(
        "-t",
        "--template",
        type=argparse.FileType("r"),
        nargs="?",
        const=False,
        help="HTML template file",
    )
    parser.add_argument(
        "file", nargs=1, type=argparse.FileType("r"), help="source file to process"
    )
    args = parser.parse_args()
    file = args.file[0]
    # language hardcoded to Python for now
    with file as f:
        code = f.read()
    chunk_type, chunks = extract_chunks(code, "#", ('"""', '"""'))

    if args.markdown is not None:
        markdown_file = args.markdown or open(f"{file.name}.md", "w")
        with markdown_file as f:
            f.write(f"# {file.name}\n\n" + to_markdown(chunk_type, chunks, "py"))

    if args.html is not None:
        if args.template and args.template:
            template_file = args.template
        else:
            template_file = open("template.html", "r")
        with template_file as f:
            template = f.read()
        html_file = args.html or open(f"{file.name}.html", "w")
        with html_file as f:
            f.write(to_html(chunk_type, chunks, "py", file.name, template))


if __name__ == "__main__":
    main()
